import { CLOUDINARY_BASE_URL, pitchtember_url } from './const';

export const EVENTS_DATA = [
  {
    id: 'pitchverse-2026',
    title: 'Pitchverse 2026',
    tagline: 'Where Fiction Gets Funded',
    category: 'Competition',
    status: 'Past',
    date: '19/09/2026',
    startDate: '2026-09-19',
    endDate: null,
    time: 'Patna Campus: TBD | Bihta Campus: TBD',
    venue: 'Patna Campus (CV Raman Hall) & Bihta Campus',
    mode: 'In-Person',
    image: 'https://res.cloudinary.com/ddb6lsyht/image/upload/v1790505907/Pitchverseposter2026.png',
    url: '/timeline',
    description: 'An unconventional entrepreneurship event where fiction meets venture capital. Participants step into the roles of iconic fictional characters and pitch their impossible, absurd, or extraordinary products as if they were real startups seeking investment.',
    highlights: [
      'Cosplay and fictional product pitching',
      'High-energy negotiation and venture capital simulation',
      'Blending culture, creativity, investment, and entertainment'
    ],
    speakers: [
      { name: 'Prof. Bharat Gupta', role: 'Professor-In-Charge, IC NITP' }
    ],
    eligibility: 'All NIT Patna students, aspiring student entrepreneurs, and creators.'
  },
  {
    id: 'orientation-2023',
    title: 'Orientation Session 2023',
    tagline: 'Welcoming New Innovators & Startup Founders',
    category: 'Workshop',
    status: 'Past',
    date: '21/09/2023',
    startDate: '2023-09-21',
    endDate: null,
    time: '04:00 PM - 06:30 PM IST',
    venue: 'CV Raman Hall',
    mode: 'In-Person',
    image: `${CLOUDINARY_BASE_URL}/v1782890669/orientation_fdo0yp.jpg`,
    url: '/timeline',
    description:
      'Orientation session for incoming student founders and innovators introducing incubation center facilities, Tinkering Lab access, and funding guidance.',
    highlights: [
      'Introduction to Incubation Center support pillars.',
      'Interactive Q&A with student coordinators and faculty mentors.',
      'Overview of prototype seed grants and lab hardware facilities.',
    ],
    speakers: [
      { name: 'Prof. Bharat Gupta', role: 'Professor-In-Charge, IC NITP' },
    ],
    eligibility: 'All NIT Patna students and aspiring student entrepreneurs.',
    sponsors: [
      {
        id: 'microsoft',
        name: 'Microsoft',
        shortName: 'Microsoft',
        tier: 'Technology Partner',
        isHighlighted: true,
        logoUrl: 'https://1000logos.net/wp-content/uploads/2017/04/Microsoft-Logo.png',
        website: 'https://www.microsoft.com/',
        description:
          'Supporting student innovation through developer tools, cloud technologies, AI resources, and learning programs.',
        perk: 'Developer & Learning Resources',
      },
      {
        id: 'github-education',
        name: 'GitHub Education',
        shortName: 'GitHub',
        tier: 'Developer Partner',
        isHighlighted: true,
        logoUrl: 'https://cdn.simpleicons.org/github',
        website: 'https://education.github.com/',
        description:
          'Helping students learn modern software development through GitHub tools, repositories, collaboration, and the Student Developer Pack.',
        perk: 'Student Developer Pack',
      },
      {
        id: 'aws-educate',
        name: 'AWS Educate',
        shortName: 'AWS Educate',
        tier: 'Cloud Partner',
        isHighlighted: false,
        logoUrl: 'https://1000logos.net/wp-content/uploads/2025/03/Amazon-Web-Services-Logo.png',
        website: 'https://aws.amazon.com/education/awseducate/',
        description:
          'Providing students with cloud learning resources and practical exposure to AWS technologies and infrastructure.',
        perk: 'Cloud Learning Resources',
      },
    ],
  },
  {
    id: 'pitchtember-2023',
    title: 'PitchTember 2023',
    tagline: 'Flagship National Startup Pitching Competition',
    category: 'Competition',
    status: 'Past',
    date: '24/11/2023 to 18/12/2023',
    startDate: '2023-11-24',
    endDate: '2023-12-18',
    time: '10:00 AM - 06:00 PM IST',
    venue: 'CV Raman Hall',
    mode: 'Hybrid',
    image: `${CLOUDINARY_BASE_URL}/v1782890669/pitchtember_ax6djs.jpg`,
    url: pitchtember_url,
    description:
      'The annual flagship startup pitching event at NIT Patna bringing together promising early-stage founders, angel investor panels, and enterprise mentors.',
    highlights: [
      'National startup pitch presentations before investor panel.',
      'Incubation seed support and mentorship awards.',
      'Keynotes on fundraising strategy and MVP validation.',
    ],
    speakers: [
      { name: 'Antesh Anand', role: 'Founder, Brand Medix' },
    ],
    eligibility: 'Open to student founders and early-stage startup teams.',
    sponsors: [
      {
        id: 'aws-startups',
        name: 'AWS for Startups',
        shortName: 'AWS Startups',
        tier: 'Cloud Partner',
        isHighlighted: true,
        logoUrl: 'https://1000logos.net/wp-content/uploads/2025/03/Amazon-Web-Services-Logo.png',
        website: 'https://aws.amazon.com/startups/',
        description:
          'Supporting early-stage startups with cloud infrastructure, technical resources, and startup-focused programs.',
        perk: 'AWS Cloud Credits',
      },
      {
        id: 'razorpay',
        name: 'Razorpay',
        shortName: 'Razorpay',
        tier: 'Fintech Partner',
        isHighlighted: true,
        logoUrl: 'https://cdn.simpleicons.org/razorpay',
        website: 'https://razorpay.com/',
        description:
          'Helping startups build and scale digital payment infrastructure with reliable payment and business solutions.',
        perk: 'Startup Payment Support',
      },
      {
        id: 'zoho',
        name: 'Zoho',
        shortName: 'Zoho',
        tier: 'Business Technology Partner',
        isHighlighted: false,
        logoUrl: 'https://cdn.simpleicons.org/zoho',
        website: 'https://www.zoho.com/',
        description:
          'Providing startups and student founders with business software for collaboration, productivity, customer management, and operations.',
        perk: 'Business Productivity Tools',
      },
      {
        id: 'nvidia-inception',
        name: 'NVIDIA Inception',
        shortName: 'NVIDIA',
        tier: 'Deep Tech Partner',
        isHighlighted: false,
        logoUrl: 'https://cdn.simpleicons.org/nvidia',
        website: 'https://www.nvidia.com/en-us/startups/',
        description:
          'Supporting innovative startups working with artificial intelligence, accelerated computing, and deep technologies.',
        perk: 'AI & Deep-Tech Resources',
      },
    ],
  },
  {
    id: 'stock-market-simulation-2024',
    title: 'Stock Market Simulation',
    tagline: 'Real-Time Financial Markets & Investment Challenge',
    category: 'Competition',
    status: 'Past',
    date: '09/02/2024',
    startDate: '2024-02-09',
    endDate: null,
    time: '02:00 PM - 06:00 PM IST',
    venue: 'Online',
    mode: 'Online',
    image: `${CLOUDINARY_BASE_URL}/v1782890671/sms_a5537x.jpg`,
    url: '/timeline',
    description:
      'An interactive online virtual trading challenge giving participants hands-on experience in portfolio management, risk evaluation, and equity analysis.',
    highlights: [
      'Real-time virtual stock market simulation environment.',
      'Cash prizes and certificates for top performing portfolio managers.',
      'Expert session on equity valuation and risk management.',
    ],
    speakers: [
      { name: 'Dr. Amitesh Kumar', role: 'Faculty Advisor' },
    ],
    eligibility: 'Open to all students interested in finance, trading, and markets.',
    sponsors: [
      {
        id: 'zerodha',
        name: 'Zerodha',
        shortName: 'Zerodha',
        tier: 'Trading Education Partner',
        isHighlighted: true,
        logoUrl: 'https://cdn.simpleicons.org/zerodha',
        website: 'https://zerodha.com/',
        description:
          'India-based financial services platform supporting investor education and awareness around markets, trading, and investing.',
        perk: 'Market Learning Resources',
      },
      {
        id: 'nse-india',
        name: 'National Stock Exchange of India',
        shortName: 'NSE',
        tier: 'Market Education Partner',
        isHighlighted: true,
        logoUrl: 'https://mma.prnewswire.com/media/1425829/NSE_Logo.jpg?w=200',
        website: 'https://www.nseindia.com/',
        description:
          'India’s leading stock exchange providing market infrastructure, financial education initiatives, and investor awareness resources.',
        perk: 'Financial Market Education',
      },
      {
        id: 'tradingview',
        name: 'TradingView',
        shortName: 'TradingView',
        tier: 'Market Analytics Partner',
        isHighlighted: false,
        logoUrl: 'https://cdn.simpleicons.org/tradingview',
        website: 'https://www.tradingview.com/',
        description:
          'Providing powerful charting, market analysis, and financial visualization tools for participants learning about financial markets.',
        perk: 'Market Analysis Tools',
      },
      {
        id: 'moneycontrol',
        name: 'Moneycontrol',
        shortName: 'Moneycontrol',
        tier: 'Financial Media Partner',
        isHighlighted: false,
        logoUrl: 'https://images.moneycontrol.com/static-mcnews/2017/03/MC-Logo-770x433.jpg?impolicy=website&width=770&height=431',
        website: 'https://www.moneycontrol.com/',
        description:
          'Financial information platform providing market news, company information, financial data, and investment insights.',
        perk: 'Market Information Access',
      },
    ],
  },
  {
    id: 'hack-the-future-2024',
    title: 'Hack The Future 2024',
    tagline: '36-Hour National Level Hackathon',
    category: 'Hackathon',
    status: 'Upcoming',
    date: '15/04/2024 to 17/04/2024',
    startDate: '2024-04-15',
    endDate: '2024-04-17',
    time: '09:00 AM - 09:00 PM IST',
    venue: 'Computer Center, NIT Patna',
    mode: 'In-Person',
    image: `${CLOUDINARY_BASE_URL}/v1782890669/pitchtember_ax6djs.jpg`,
    url: '/timeline',
    description: 'Join the ultimate 36-hour coding marathon. Build innovative solutions for real-world problems using modern tech stacks.',
    highlights: [
      '36 hours of continuous coding.',
      'Free meals, swag, and cloud credits.',
      'Cash prizes worth ₹1,00,000.'
    ],
    speakers: [],
    eligibility: 'Open to all university students.',
    sponsors: [
      {
        id: 'github',
        name: 'GitHub',
        shortName: 'GitHub',
        tier: 'Developer Partner',
        isHighlighted: true,
        logoUrl: 'https://cdn.simpleicons.org/github',
        website: 'https://github.com/',
        description:
          'Providing developers with collaborative tools for source control, project management, open-source development, and CI/CD.',
        perk: 'Developer Tools & Resources',
      },
      {
        id: 'cloudflare',
        name: 'Cloudflare',
        shortName: 'Cloudflare',
        tier: 'Infrastructure Partner',
        isHighlighted: true,
        logoUrl: 'https://cdn.simpleicons.org/cloudflare',
        website: 'https://www.cloudflare.com/',
        description:
          'Providing developers with web security, performance, networking, and edge infrastructure technologies.',
        perk: 'Web Infrastructure Resources',
      },
      {
        id: 'mongodb',
        name: 'MongoDB',
        shortName: 'MongoDB',
        tier: 'Database Partner',
        isHighlighted: false,
        logoUrl: 'https://cdn.simpleicons.org/mongodb',
        website: 'https://www.mongodb.com/',
        description:
          'Supporting hackathon teams with modern database technology for building scalable and data-driven applications.',
        perk: 'Database Resources',
      },
      {
        id: 'postman',
        name: 'Postman',
        shortName: 'Postman',
        tier: 'API Partner',
        isHighlighted: false,
        logoUrl: 'https://cdn.simpleicons.org/postman',
        website: 'https://www.postman.com/',
        description:
          'Helping developers design, test, document, and collaborate on APIs during rapid application development.',
        perk: 'API Development Tools',
      },
    ],
  }
];
